// Code generated by Prismic. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
	bento: defineAsyncComponent(() => import("./Bento/index.vue")),
	contact: defineAsyncComponent(() => import("./Contact/index.vue")),
	focus_content: defineAsyncComponent(() => import("./FocusContent/index.vue")),
	focuses: defineAsyncComponent(() => import("./Focuses/index.vue")),
	hero: defineAsyncComponent(() => import("./Hero/index.vue")),
	showcase: defineAsyncComponent(() => import("./Showcase/index.vue"))
});